### ISSUE TITLE
unexpected keyword argument 'removeClouds'

### ISSUE THREAD

**Issue by thanhgis** [samsammurphy/ee-atmcorr-timeseries#1]
Dear Sam, 

There is an issue here with 'removeClouds", either "True" or "False".

Mean Average Radiance
In [42]:

True
# earth engine request
request = request_meanRadiance(geom, startDate, stopDate, mission, removeClouds = True) # True or False for now
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-42-8213a7c11e4b> in <module>()
      1 # earth engine request
----> 2 request = request_meanRadiance(geom, startDate, stopDate, mission, removeClouds = True) # True or False for now

TypeError: request_meanRadiance() got an unexpected keyword argument 'removeClouds'

**Comment by samsammurphy** [comment]
Dear Thanhgis,

Thanks for reporting. Did you pull in the latest source code?

`git pull`

'removeClouds' is only available in the latest version. lmk, so I can fix it, if it is something else

**Comment by thanhgis** [comment]
Dear Sam, 

I did not "pull", but did "clone". 

Please see attached screenshot for further detail. Did I do something wrong? Or, should I copy "atmcorr" to site-packages in Python Libs?

![sam](https://user-images.githubusercontent.com/7676117/28151452-dbe18e9e-67c4-11e7-9e85-8f051386939d.png)
Thank you!

**Comment by samsammurphy** [comment]
Dear Thanh,

Let's try to navigate to your local copy of the git repository which, from your screen-shot, might be like this:

```
cd\

cd ee-atmcorr-timeseries
```

then run 'git pull' to make sure that you have the latest version of the source code

`git pull`


The notebook *should* now work properly..
```

cd jupyter_notebooks

jupyter-notebooks ee-atmcorr-timeseries.ipynb
```

please let me know how that goes!

Thanks !!

**Comment by thanhgis** [comment]
Dear Sam, 

Unfortunately, still same error, as in this new screeshot. Did I do correct what you instructed? 

BTW, "jupyter-notebooks ee-atmcorr-timeseries.ipynb" should be corrected to "jupyter notebook ee-atmcorr-timeseries.ipynb"
![image](https://user-images.githubusercontent.com/7676117/28155806-6e8d6212-67da-11e7-907f-d69d51372460.png)

**Comment by samsammurphy** [comment]
Dear Thanh,

Looks like you did everything right. 

It's an interesting problem, will investigate and get back to you.

**Comment by samsammurphy** [comment]
Ok.. I can't replicate the error on my machine and there is no obvious answer via google.

Here is my proposed solution: make the 'removeClouds'  parameter positional (i.e not a keyword).. i.e. like the other variables passed into the request_meanRadiance() function.

The updates have been made, hopefully pulling in the source code will do the trick:

```
cd\
cd ee-atmcorr-timeseries
git pull
cd jupyter_notebooks
jupyter-notebook ee-atmcorr-timeseries.ipynb
```

feedback is valuable. please let me know how that goes

**Comment by thanhgis** [comment]
Dear Sam, 

Did you block your repository? Or somethink happened with it. Please check. 

C:\>git clone https://github.com/samsammurphy/ee-atmcorr-timeseries.gi
Cloning into 'ee-atmcorr-timeseries.gi'...
remote: Repository not found.
fatal: repository 'https://github.com/samsammurphy/ee-atmcorr-timeseries.gi/' no
t found

I tried several times, within last hour but not success.

Thank you!

**Comment by samsammurphy** [comment]
I think you are missing a 't' at the end of the repository name: https://github.com/samsammurphy/ee-atmcorr-timeseries.git

(also) you don't have to clone the repository every time, you can just run the 'git pull' command (when inside the local git directory) to get the latest version.

**Comment by thanhgis** [comment]
I am sorry for my stupid feedback.
(FYI, when I 'git pull', it cannot overwrite, that why I have to clone again).

It works now. 

I am thinking to combine this one with your Atmospheric Correction. Do you have any suggestion?

**Comment by samsammurphy** [comment]
Great to hear it works!

This time series is already atmospherically corrected.

Also, the results are automatically saved to an excel file in a subdirectory called 'files' (if it doesn't exist the code will create that directory in your github repository folder) .. will add this to the documentation
