### ISSUE TITLE
Bands missing

### ISSUE THREAD

**Issue by jassantos** [samsammurphy/ee-atmcorr-timeseries#3]
Hello again Sir Sam,

I looked into this repository. It seems the output for Sentinel 2 is only 6 bands, even though it is originally 13 bands. Can we output the processed 13 bands?

**Comment by samsammurphy** [comment]
Hello. apologies for delay. The 6 bands used are the ones that exist on both Sentinel2 and Landsat (i.e. blue, green, red, nir, swir1, swir2). This is to look back further into the past.

Outputing the additional bands would require some tweeks. 

Note that 3 of these additional bands are officially used for atmospheric correction (i.e. 1, 9 and 10) so they will not typically represent surface conditions very well but they are also not used as inputs to improve results. Although they are (presumably) used by the official ESA solution (i.e. L2A) to improve their surface reflectance retrievals.
